@extends($lite ? 'layouts.blank': 'layouts.app')

@section('content')
  <div style="font-size: 12px">
    <div style="margin-bottom: 5px">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget arcu dictum varius duis at. Vulputate eu scelerisque felis imperdiet proin fermentum. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Amet consectetur adipiscing elit duis tristique sollicitudin. Sed risus pretium quam vulputate dignissim suspendisse. Gravida neque convallis a cras semper.</div>
    <div style="margin-bottom: 5px">Leo vel orci porta non pulvinar. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Hac habitasse platea dictumst quisque sagittis purus. Id semper risus in hendrerit gravida rutrum quisque. Ultrices eros in cursus turpis. Posuere morbi leo urna molestie at elementum eu facilisis sed. Consequat ac felis donec et odio pellentesque diam. Augue lacus viverra vitae congue eu consequat. Ut morbi tincidunt augue interdum velit euismod. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Vulputate ut pharetra sit amet aliquam. Nunc mi ipsum faucibus vitae aliquet.</div>
    <div style="margin-bottom: 5px">Elit ut aliquam purus sit amet. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Habitant morbi tristique senectus et netus et malesuada fames ac. A iaculis at erat pellentesque adipiscing. Vel orci porta non pulvinar neque. Consequat semper viverra nam libero justo laoreet sit amet cursus. Tempus urna et pharetra pharetra massa massa. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Malesuada nunc vel risus commodo viverra maecenas accumsan. Lorem dolor sed viverra ipsum nunc aliquet. Sit amet nisl purus in mollis nunc. Tempor commodo ullamcorper a lacus vestibulum. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque.</div>
    <div style="margin-bottom: 5px">Urna et pharetra pharetra massa massa ultricies mi quis. Non odio euismod lacinia at. Pretium lectus quam id leo in vitae. Eget arcu dictum varius duis at. Enim eu turpis egestas pretium aenean pharetra magna. Adipiscing elit ut aliquam purus. Odio euismod lacinia at quis risus sed vulputate odio. In egestas erat imperdiet sed. Mi sit amet mauris commodo quis imperdiet massa. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Ipsum consequat nisl vel pretium lectus quam id. Arcu cursus vitae congue mauris rhoncus aenean vel. Mi tempus imperdiet nulla malesuada. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Urna id volutpat lacus laoreet. Elementum sagittis vitae et leo. Egestas sed tempus urna et pharetra pharetra massa massa ultricies.</div>
    <div style="margin-bottom: 5px">Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Nibh nisl condimentum id venenatis a condimentum. Facilisis gravida neque convallis a cras semper. Sit amet mauris commodo quis imperdiet massa tincidunt nunc. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Elementum facilisis leo vel fringilla est ullamcorper. Vel pretium lectus quam id leo in. Massa ultricies mi quis hendrerit. Congue eu consequat ac felis.</div>
  </div>
@endsection